apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: ollama
spec:
  storageClassName: nfs-server
  accessModes: ["ReadWriteOnce"]  
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      nodeSelector:
        type: "ia"
      containers:
      - name: ollama
        image: ollama/ollama:0.17.6
        ports:
        - containerPort: 11434
          name: api
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "6"       
            memory: "14Gi" # Límite cercano al máximo del Worker 2
        volumeMounts:
        - name: ollama-storage
          mountPath: /root/.ollama
      volumes:
      - name: ollama-storage
        persistentVolumeClaim:
          claimName: ollama-data
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: ollama
spec:
  selector:
    app: ollama
  ports:
  - protocol: TCP
    port: 11434
    targetPort: 11434
